name: Node.js CI

on:
  push:
    branches: [ main, master ]
    
jobs:
  ui:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    
    steps:
    
    - uses: actions/checkout@v2
      
    - name: Set Node.js 14.x <= 
      uses: actions/setup-node@v3
      with:

      # Runs a single command using the runners shell
      # - name: Set-Version
      #   run: |
      #     echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      #     echo $GITHUB_ENV
      # pull buildx       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # authorize ssl certificates for login
      - name: set cert
        run: bash server/cert.sh
      
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      # login to harbor
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_BOT_ID }}
          password: ${{ secrets.HARBOR_BOT_PW }}
      # start build and push
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.HARBOR_REGISTRY }}/seo/shell:latest
      - name: Push the tagged Docker image
        run: docker push ${{ secrets.HARBOR_REGISTRY }}/seo/shell:latest
        
  deploy:
    # The type of runner that the job will run on
    needs: docker
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Webhook
        run: curl -s -d "payload={\"feel\":\"WTF\"}" "${{ secrets.WEB_HOOK_TARGET }}"
      
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#           SLACK_ICON: https://github.com/rtCamp.png?size=48 # later add favicon
          SLACK_TITLE: 'deployed new version for seo project'
          SLACK_MESSAGE: ${{ github.event.head_commit.title }} ${{ github.event.head_commit.message }}
          SLACK_USERNAME: MySNS-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 
  apply-if-failed:
    runs-on: ubuntu-latest
    needs: [ui, docker, deploy]
    if: always() && (needs.apply.result == 'failure')
    steps:
      - name: WEBHOOK apply was failed
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_CONTEXT"
      - name: Slack Notification Failed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF2D00' # or a specific color like 'good' or '#ff00ff'
#           SLACK_ICON: https://github.com/rtCamp.png?size=48 # later add favicon
          SLACK_TITLE: 'github cd/ci was failed'
          SLACK_MESSAGE: ${{ github.event.head_commit.title }} ${{ github.event.head_commit.message }}
          SLACK_USERNAME: security-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        

